<?php //[STAMP] ae93f24729544d637420b0ec1bc4b57f
namespace ByTIC\Common\Tests\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();


}
